name: Build coop

on:
    workflow_dispatch:

jobs:
    build-linux:
        if: ${{ github.event_name == 'workflow_dispatch' || contains(github.event.head_commit.message, '[build]') }}
        runs-on: ubuntu-22.04
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Install dependencies
              run: |
                sudo apt update
                sudo apt install -y build-essential git python3 libglew-dev libsdl2-dev libz-dev libcurl4-openssl-dev zip

            - name: Build the game
              run: make -j$(nproc)

            - name: Generate hash
              run: |
                cd tools
                g++ -std=c++17 -o hash_file hash_file.cpp
                echo "::notice ::$(./hash_file ../build/us_pc/sm64coopdx)"
            
            - name: Zip the game
              run: |
                cd ./build/us_pc
                zip -r sm64coopdx_Linux.zip dynos lang mods palettes libdiscord_game_sdk.so sm64coopdx

            - name: Upload artifact
              uses: actions/upload-artifact@v4
              with:
                name: sm64coopdx-linux
                path: ./build/us_pc/sm64coopdx_Linux.zip
